### ISSUE TITLE
Build failed for Gradlew Paperclip

### ISSUE THREAD

**Issue by ethsmith** [NFT-Worlds/Server#1]
**Describe the bug**
Receive this error when trying to build Paperclip with Gradle

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':NFT-Worlds-Server:shadowJar'.
> Failed to read upstream data.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```

**To Reproduce**
Run `./gradlew paperclip`

**Expected behavior**
The Paperclip jar to build successfully

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: Latest commit

**Comment by ghost** [comment]
NFTs

**Comment by jacobp925** [comment]
Try applying the patches first.
