### ISSUE TITLE
Pufferfish Patch Copyright Notice/ GPL License - 0046-Async-Entities.patch

### ISSUE THREAD

**Issue by Avedith** [NFT-Worlds/Server#2]
**Describe the issue**

It has come to the attention of a variety of people within the Minecraft community that NFTWorlds server implementation contains a fork from Pufferfish without appropriate credit being given to the original owners of the patch (0046-Async-Entities.patch). 
By definition this is in violation of the GPL-3.0 license as used in the pufferfish [repository](https://github.com/pufferfish-gg/Pufferfish).

[Original Pufferfish Patch](https://github.com/pufferfish-gg/Pufferfish/blob/f053fd35a2820aefd488666b993b600d3c2cfcbb/patches/server/0008-Optimize-mob-spawning.patch#L144-L167) (LEFT HAND SIDE)
vs
[NFTWorlds' Patch](https://github.com/NFT-Worlds/Server/blob/main/patches/server/0046-Async-Entities.patch#L246-L265) (RIGHT HAND SIDE)

![unknown](https://user-images.githubusercontent.com/65852834/151267052-d742ad58-552f-40a9-88c8-12ca8da83857.png)

**Mentions:**
@jacobp925

**Comment by MWHunter** [comment]
Other patches that were taken without proper copyright headers is Patch 42 from old Airplane, Patch 47 from old Pufferfish (this one I am somewhat unsure about), and Patch 66 which is stolen from Pufferfish.

Patch 66 is especially interesting as the original patch had a comment marking it as a pufferfish change.  This comment is no longer present in NFTWorlds.  So either it was removed or both developers found the same optimization.

**Comment by jacobp925** [comment]
Thank you, but this has already been addressed directly by the developers, headers are being added for patches 46, 47, and 66. There’s also credit in the readme file stating that this is a fork.
