### ISSUE TITLE
no main manifest attribute, in NFT-Worlds-Server-1.17.1-R0.1-SNAPSHOT.jar

### ISSUE THREAD

**Issue by cryptonft** [NFT-Worlds/Server#4]
**Describe the bug**
On running:

 java -Xms2G -Xmx2G -jar NFT-Worlds-1.17.1-R0.1-SNAPSHOT
 java -Xms2G -Xmx2G -jar NFT-Worlds-1.17.1-R0.1-SNAPSHOT.jar

Error:
no main manifest attribute, in NFT-Worlds-Server-1.17.1-R0.1-SNAPSHOT.jar

**To Reproduce**
1. Go to 'C:\XXXXX\NFT-Worlds-Server\build\libs'
2. Click on the .jar file OR run above command in Windows CMD within above directory

**Expected behavior**
Expect EULA file created

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 11

**Comment by jacobp925** [comment]
Run NFT-Worlds-Server-reobf.jar instead.
